const types = {
  CURRENT_WEATHER_REQUEST: 'CURRENT_WEATHER_REQUEST',
  CURRENT_WEATHER_SUCCESS: 'CURRENT_WEATHER_SUCCESS',
  CURRENT_WEATHER_FAILURE: 'CURRENT_WEATHER_FAILURE',
  CURRENT_WEATHER_DISMISS: 'CURRENT_WEATHER_DISMISS',
  FORECAST_WEATHER_REQUEST: 'FORECAST_WEATHER_REQUEST',
  FORECAST_WEATHER_SUCCESS: 'FORECAST_WEATHER_SUCCESS',
  FORECAST_WEATHER_FAILURE: 'FORECAST_WEATHER_FAILURE',
};

export default types;
